export const SET_TICKETS = 'TICKETS/SET_TICKETS';
export const FETCH_TICKETS = 'TICKETS/FETCH_TICKETS';
export const FILTER_TICKETS_BY_STOPS = 'TICKETS/FILTER_TICKETS_BY_STOPS';

export const SHOW_LOADER = 'TICKETS/SHOW_LOADER';
export const HIDE_LOADER = 'TICKETS/HIDE_LOADER';

export const FILTER_TYPES = 'TICKETS/FILTER_TYPES';

